# This workflow will run when changes are detected in the `main` branch, which
# must include an update to the `version.txt` file. The workflow can also be
# manually triggered by a repository maintainer. This workflow will create a
# GitHub release with the release notes from the latest version of the Harmony
# Autotester.
name: Publish Harmony Autotester GitHub Release

on:
  push:
    branches: [ main ]
    paths: version.txt
  workflow_dispatch:

jobs:
  publish_github_release:
    name: "Publish GitHub Release"
    runs-on: ubuntu-latest
    environment: production
    permissions:
      # write permission is required to create a GitHub release
      contents: write
      id-token: write
      packages: write

    steps:
      - name: Checkout nasa/harmony-autotester repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Extract semantic version number
        run: echo "SEMANTIC_VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Extract release version notes
        run: |
          version_release_notes=$(./bin/extract-release-notes.sh)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "${version_release_notes}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Publish GitHub release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ env.RELEASE_NOTES }}
          commit: main
          name: Version ${{ env.SEMANTIC_VERSION }}
          tag: ${{ env.SEMANTIC_VERSION }}
