# This workflow will trigger all tests to be executed using the production
# environment for Harmony, Earthdata Login and CMR.
name: Production Harmony Autotester execution

on:
  schedule:
    # Currently scheduled every morning at 4:05am UTC.
    - cron: "5 4 * * *"

jobs:
  run_production_tests:
    runs-on: ubuntu-latest
    name: Production Harmony Autotester execution
    uses:
      ./.github/workflows/test_all_associated_collections.yaml
    with:
      harmony_environment: production
